# Generated by Django 3.2.7 on 2021-09-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=200)),
                ('email1', models.CharField(max_length=200)),
                ('email2', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
