# Generated by Django 3.2.7 on 2021-09-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_members_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('supporter', 'supporter'), ('volunteer', 'volunteer'), ('comp', 'comp'), ('board', 'board')], default='supporter', max_length=10),
        ),
    ]
