# Generated by Django 3.2.7 on 2021-09-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210904_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
