# Generated by Django 3.2.7 on 2021-09-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('supporter', 'supporter'), ('volunteer', 'volunteer'), ('honorary', 'honorary'), ('pam_staff', 'pam staff'), ('board', 'board')], default='supporter', max_length=10),
        ),
    ]
