# Generated by Django 3.2.7 on 2021-09-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_membership_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='name1',
        ),
        migrations.AddField(
            model_name='member',
            name='name2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
