# Generated by Django 3.2.7 on 2021-09-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_print_optout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='print_optout',
            new_name='directory_optout',
        ),
    ]
