# Generated by Django 3.2.7 on 2021-09-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_zip_member_postal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='postal',
            new_name='postal_code',
        ),
    ]
