# Generated by Django 3.2.7 on 2021-09-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_rename_postal_member_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('supporter', 'supporter'), ('volunteer', 'volunteer'), ('honorary', 'honorary'), ('PAM staff', 'PAM staff'), ('board', 'board')], default='supporter', max_length=10),
        ),
    ]
