# Generated by Django 3.2.7 on 2021-09-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_member_membership_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='title',
            new_name='byline',
        ),
    ]
