# Generated by Django 3.2.7 on 2021-09-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_rename_title_member_byline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
