# Generated by Django 3.2.7 on 2021-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_member_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone_number',
            new_name='phone_number1',
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
