# Generated by Django 3.2.7 on 2021-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20210904_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
