# Generated by Django 3.2.7 on 2021-09-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_member_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reason_for_review',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
