# Generated by Django 3.2.7 on 2021-09-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_member_reason_for_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
