# Generated by Django 3.2.7 on 2021-09-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20210904_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fname1',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lname1',
            new_name='sortby',
        ),
    ]
